package weather

var Garbage = []string{"blyaa", "blyaaa", "loh", "pidor", "mraz", "ublyudok", "mudak", "shluha", "tvar", "zhlob", "govnyuk", "debil",
	"durak", "pridurak", "idiot", "tupoy", "merzavec", "gadina", "chmo", "mrazota", "svinya",
	"gondon", "prost", "eblan", "blyad", "pizdec", "hnuy", "khuila", "kurva", "psikh", "chekushka",
	"padla", "chern", "shlyukh", "syka", "kal", "svoloch", "mudila", "pizda", "ebat", "nahuy",
	"hovno", "zhopa", "bastard", "huila", "puk", "srat", "kretin", "durik", "suka", "zvezdun",
	"balbes", "zhrat", "mrazota", "blya", "zhit", "tuporyl", "zver", "dolboeb", "zhadn", "yanit",
	"tuporyloye", "mlat", "ubozhestvo", "derevnya", "koshmar", "svechka", "psar", "kidalovo",
	"lozh", "kulak", "xyiii", "xyi", "xuy", "ubyven", "trutnya", "kobyla", "obrazina",
	"lebedev", "uzhasno", "kudryash", "pusk", "ebateln", "pyan", "gremuch", "sras", "puzata",
	"mokh", "zhalez", "lemy", "kurka", "tumann", "sol", "nevedom", "topor", "chort", "pykh",
	"zhurk", "volk", "puza", "blyaaaa", "krysy", "psarney", "lyagush", "karas", "toshch", "obrazin",
	"potr", "ulov", "zhitye", "mrak", "khnyk", "nek", "obezdyanny", "skazoch", "tsarap",
	"prigor", "kholodok", "balka", "kluzhen", "khrebet", "sukno", "zabash", "pykhta",
	"kozlyak", "zhalky", "urody", "zolotnik", "sakharn", "stuch", "beshen", "totk",
	"zadrot", "ebanuty", "kratk", "odnoryl", "tufel", "bych", "pykal", "ryash", "plok",
	"madrost", "den", "zhirk", "svolotch", "opredelenny", "perst", "verta", "baryga",
	"komar", "nedotyapa", "okhlos", "pizdobol", "kurya", "begemot", "zaraz", "pysh",
	"gavn", "idiotka", "tuporyl", "zolushk", "nevedoma", "motyla", "pykhay", "cherny",
	"tabun", "trotsky", "dverolom", "lopuh", "pizdun", "okrug", "govnits", "melanch",
	"shirok", "kuritsa", "lopukh", "kal", "padle", "lomak", "gavno", "kozlyak", "merzl",
	"dermo", "morda", "zhyr", "ziryu", "rasplet", "mutka", "skotina", "ubozh",
	"plokha", "mlek", "nakhuy", "pyzh", "zelyon", "baryga", "tuk", "podkhvalit",
	"govna", "pidaras", "khutor", "srat", "kukl", "pyanstv", "volk", "vedun", "gadyuka",
	"kot", "tsarapak", "svod", "pridurok", "dozh", "kukha", "muza", "kobyl", "khrebet",
	"prokhindy", "lysyak", "marod", "pion", "tsup", "khrap", "zabrash", "prykh", "zabr",
	"pechatn", "dolbanut", "naks", "лох", "говно", "пидор", "мразь", "ублюдок", "мудак", "шлюха", "тварь", "жлоб", "говнюк", "дебил",
	"дурак", "придурок", "идиот", "тупой", "мерзавец", "гадина", "чмо", "мразота", "свинья",
	"гондон", "проститутка", "заебал", "ебанат", "курва", "ублюдина", "хуесос", "пошёл", "хрен",
	"хуй", "сдохни", "пошёл нахуй", "еблан", "хуила", "хуеплёт", "ебанутый", "блядина", "ебаный",
	"пизда", "нахуй", "пиздец", "ебарь", "пидрила", "говнюк", "тупица", "балбес", "болван", "мудила",
	"ёбнутый", "хуёвый", "ссать", "ёбтвоюмать", "падла", "козёл", "шлюшка", "ублюдская", "жопа",
	"чёрт", "пиздюк", "дрянь", "скотина", "козлина", "мразиш", "мразота", "пиздеть", "хуякать",
	"дебилизм", "гавно", "тупая мразь", "гнида", "паскуда", "петух", "сукин сын", "гнида", "сука",
	"паскуда", "хреновина", "паскудина", "хуесосина", "пиздобол", "хуебесие", "хуесранье", "еблана",
	"жируха", "гнида тупая", "пиздабол", "пиздопроебина", "дебилушка", "хренов", "падло", "поганец",
	"поганый", "сволота", "говнючка", "ёбаная мразь", "пиздобратия", "пиздень", "хуеглот", "пидорасина",
	"засранец", "мудачье", "скот", "падлючка", "говнистый", "пиздоватый", "хуярить", "чепуха",
	"пиздюковатый", "пиздоплюй", "пиздуй", "пизденыш", "чмошник", "loh", "pidar", "fuck", "suck", "shit", "asshole", "bitch", "idiot", "dick",
	"сука", "блядь", "бля", "говно", "ублюдок", "мудак", "пидор", "шлюха", "ссать", "мразь",
	"чмо", "жопа", "тварь", "дурак", "идиот", "тупой", "козёл", "мерзавец", "пиздец", "ебаный",
	"хуесос", "нахуй", "тупица", "кретин", "псих", "ёбнутый", "тупой", "курва", "жлоб", "сволочь",
	"падла", "чёрт", "свинья", "гадина", "проститутка", "ублюдина", "мразота", "мудила", "пизда",
	"еблан", "хрен", "гондон", "мразь", "придурок", "говнюк", "балбес", "болван", "чмо", "дебил",
	"заебал", "мудачье", "пошел", "сдохни", "сучка", "тупица", "псих", "козёл", "гнида", "хуила",
	"blya", "douchebag", "faggot", "motherfucker", "nigger", "whore", "slut", "scumbag", "wanker",
	"arsehole", "bollocks", "twat", "prick", "cunt", "slag", "wanker", "git", "tosser", "screwup",
	"cock", "pussy", "retard", "jerk", "moron", "fool", "knob", "clown", "pussy", "киска"}
